### ISSUE TITLE
How to create multiple objects synchronously?

### ISSUE THREAD

**Issue by Kadrian** [aexmachina/factory-girl#52]
I'm looking for something like:
```
const user = factory.create('user');
const client = factory.create('client');
const books = factory.createMany('book', 10);

// Now that everything has been created, let's proceed with our mocha test
```

Instead, what I'm ending up doing in my mocha test is something like:
```
before((done) => {
  factory.create('user', (user) => {
    this.user = user;
    factory.create('client', (client) => {
      this.client = client;
      factory.createMany ... 
          // Call done() somewhere
    });
  });
});
```

Can you help me how multiple create calls are supposed to be used? I would also appreciate some examples in the README. Great job with the lib by the way ;)

**Comment by chetanism** [comment]
Hi @Kadrian, the library relies on DB to persist models, which usually is asynchronous. You may instead write multiple before blocks. e.g.
```javascript
before((done) => {
  factory.create('user', () => { done(); }
});
before((done) => {
  factory.create('client', () => { done(); }
});
...
```
Otherwise, you may [promisify](https://github.com/aexmachina/factory-girl#like-promises) the library either using bluebird or [es6-promisify](https://www.npmjs.com/package/es6-promisify), and then do:

```javascript
before((done) => {
  const userP = factory.create('user');
  const clientP = factory.create('client');
  const booksP = factory.createMany('book');
  Promise.all([userP, clientP, booksP]).then(() => done());
}
```

If you can use es7 [async/await](https://jakearchibald.com/2014/es7-async-functions/) via [babel](https://babeljs.io/), you may then also do (after promisifying):

```javascript
before(async (done) => {
  const user = await factory.create('user');
  const client = await factory.create('client');
  const books = await factory.createMany('book');
  done();
}
```

**Comment by Kadrian** [comment]
Aha, thanks @chetanism, that's what I was looking for! I think this totally belongs into the README! I didn't know that I HAD to "promisify" the library to really leverage its power. What's the rationale for not making this concise code the default / suggested way of using factory-girl? If it's because there are multiple implementations for promises and you would like people to be able to choose, I understand. But now I think people are forced to choose before they're able to actually use all the power of this library.
In any case, I wish this was being made a little clearer for beginners like me 😁  Thanks again!

**Comment by chetanism** [comment]
This library was originally forked from [factory-lady](https://github.com/petejkim/factory-lady), and continues to keep most of the code. However, we have been working on rewriting  the library, keeping promises by default as you suggest!
You can take a sneak-peak at https://github.com/chetanism/factory-girl/tree/rewrite. The work is almost complete, but we still need to update the documentation. It would be great if you can provide some feedback or try it out in a dummy project (since some APIs are not compatible with current version) and report any bugs that you may find.
Once we feel the new library is ready for a release (in probably 2-4 weeks), we'll roll out a brand new v4!

**Comment by aexmachina** [comment]
factory-girl 4.0.0-beta.1 is now available. With the new version you can:

```js
before(() => 
  factory.create('user')
    .then(() => factory.create('client'))
);
```
