### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by lblazecki** [aexmachina/factory-girl#63]
Hello

I like your work. Factory_girl is module that is much needed in nodeJS community.
Unfortunately, I didn't managed to connect new factory_girl version with sequelize adapter factory_girl.
When do you think new stable version will be out?

**Comment by chetanism** [comment]
Hi @lblazecki, thanks for raising the issue. I suppose there are two problems to fix here: #64 and that we haven't put the new version for factory-girl-sequelize yet. Sorry for the confusion that you had to face, but we'll need another 1-2 weeks to sort everything out.

**Comment by lblazecki** [comment]
@chetanism thank you for your response :)
I am looking forward to it!

**Comment by chetanism** [comment]
Hi @lblazecki, we just managed to fix #64 as well as add a Sequelize adapter to factory girl itself.
You should be able to:
`import factory, { SequelizeAdapter } from 'factory-girl'`
Let us know in case you face any issues.

**Comment by lblazecki** [comment]
Hi @chetanism 

I faced an issue:
```
.../node_modules/factory-girl/index.js:66
      throw new Error('Invalid Model constructor passed to the factory');
      ^
Error: Invalid Model constructor passed to the factory
```

This is the line in code:
```
if (!Model || typeof Model !== 'function') {
  throw new Error('Invalid Model constructor passed to the factory');
}
```

When `typeof Model !== 'function'` is removed it's working normally, but I am not sure what are the consequences of removing it.

**Comment by chetanism** [comment]
@lblazecki, if I am right, the issue is probably because of `Sequelize` Model. FactoryGirl expects `Model` to be a constructor function that can be used to create new instances. In case of Sequelize I guess `Model.Instance` is the constructor function.

Thanks for pointing out the issue. Here is what you can do to keep things working at your end, till we get this fixed:

- update your package.json to point factory-girl to `https://github.com/chetanism/factory-girl.git#v4-sequelize-fix`
- Import factory-girl from `factory-girl/dist'
- To avoid putting `factory-girl/dist` at all places, create a wrapper script in your app and import the wrapper script wherever required, once the issue is fixed, you can easily change it back to importing from `factory-girl`

I have just pushed the updated build to the above mentioned branch. This should keep you going while we fix the issue.

**Comment by lblazecki** [comment]
@chetanism 

Thank you :)
It's working now 👍

**Comment by gunar** [comment]
It seems both #63 & #64 are resolved now. Can we haz stable version? :innocent: TY!!

**Comment by createthis** [comment]
I can't seem to get v4 working with Sequelize. I think npm installed 4.0.0-beta.7.

Here's my setup:
```javascript
var factory = require('factory-girl');
const adapter = new factory.SequelizeAdapter();
factory = factory.factory;

const Models = require('../../models');

factory.define('products', Models.products, {
  parent_name: 'MS Foo',
  priority_scale: 50, 
});
```

At this point I get `TypeError: Model is not a constructor`. I can't seem to find the magic incantation to get a sequelize model object that factory-girl finds kosher.

I'm using sequelize's `import` method to place one model per file: http://docs.sequelizejs.com/en/latest/api/sequelize/#importpath-model
You can see an example of what that looks like here: https://github.com/sequelize/express-example/blob/master/models/task.js

Any ideas?

**Comment by createthis** [comment]
I think factory-girl v4 is going about this wrong. According to the docs for Sequelize Model:

> This class should not be instantiated directly, it is created using sequelize.define, and already created models can be loaded using sequelize.import

http://docs.sequelizejs.com/en/v3/api/model/

**Comment by createthis** [comment]
Solved.

Looking at the source of the failure message, here: https://github.com/aexmachina/factory-girl/blob/7e4335330a4e85d4c6c2ecf9a881df8ff9b77965/src/adapters/DefaultAdapter.js#L4

It looked like I just wasn't initializing the SequelizeAdapter properly, so I was hitting the DefaultAdapter. I would have noticed that earlier, but I'm running my tests in mocha and it took me forever to figure out how to get a trace from Node's UnhandledPromiseRejectionWarning via the unhandledRejection event. In case anyone else is curious, just added this to the mocha test file:

```javascript
process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at: Promise', p);
  console.log('reason:', reason);
});
```

Anyway, I just needed to call `setAdapter`. Here's the working code:

```javascript
var factory = require('factory-girl');
const adapter = new factory.SequelizeAdapter();
factory = factory.factory;
factory.setAdapter(adapter);

const Models = require('../../models');

factory.define('products', Models.products, {
  name: 'Some Foo',
  priority: 50, 
});
```

**Comment by chetanism** [comment]
Hi @createthis, glad that your problem is solved. I did saw the mail for this issue, but couldn't find time to look into it. Thanks for posting the comment, it would help if someone else faces the issue.
I just have one request, if you face any issues, please open a new issue for it. Not just it would keep the discussion separate, it would also help others to find it easily if they face similar problem.

**Comment by chetanism** [comment]
@gunar, it should happen soon!

**Comment by gunar** [comment]
@chetanism what about now? :innocent:

**Comment by aexmachina** [comment]
I've published v4 :tada: Thanks everyone who's contributed to this release, and sorry it took us so long to get it released!

**Comment by hschoenburg** [comment]
@createthis THANK YOU SO MUCH FOR POSTING YOUR SOLUTION!!!!
